name: Stream Bot

on:
  workflow_dispatch:
    inputs:
      stream_url:
        description: "Stream URL"
        required: true
      rtmp_url:
        description: "RTMP URL"
        required: true

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install ffmpeg -y

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Run Extractor
        run: node extractor.js "${{ inputs.stream_url }}"

      - name: Run FFmpeg
        run: ffmpeg -re -i "$(cat stream.txt)" -f flv "${{ inputs.rtmp_url }}"
