name: Stream Bot

on:
  workflow_dispatch:
    inputs:
      stream_url:
        description: "Page URL"
        required: true
      rtmp_url:
        description: "Facebook RTMP"
        required: true

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Extract real stream
        run: node extractor.js "${{ inputs.stream_url }}"

      - name: Run FFmpeg
        run: |
          ffmpeg -re -i "$(cat stream.txt)" \
          -c:v libx264 -preset veryfast -maxrate 2500k -bufsize 5000k \
          -c:a aac -b:a 128k -f flv "${{ inputs.rtmp_url }}"
